### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by Redmega** [Chaosthebot/Chaos-Core#3]
There are many advantages to enforcing/encouraging the following of contribution guidelines.

One such example would be using [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages), which will make the commit log dead simple to read (and even use tools to parse for creating changelogs, etc).

What do you all think?

**Comment by mdcfe** [comment]
We'd (eventually) have to enforce this for PRs somehow, which would be difficult if we were to squash commits from PRs. I think we should keep contribution guidelines in Chaosthebot/Chaos-General and send people there for the guidelines - that way, we can keep a single consistent document for the whole bot.

**Comment by Redmega** [comment]
Closing this to continue the conversation in Chaosthebot/Chaos-General#2
